### ISSUE TITLE
能否写入"专辑艺术家"这个标签

### ISSUE THREAD

**Issue by ironstress** [mos9527/pyncm#17]
我用的MusicBee, 椒盐播放器等, 都是以"专辑艺术家"区分专辑的.

不写入的话会产生多个专辑

**Comment by mos9527** [comment]
![image](https://user-images.githubusercontent.com/31397301/177898494-54869cc5-d1c7-4592-87d0-6e4f5a9275cf.png)
![image](https://user-images.githubusercontent.com/31397301/177898506-e05cf332-f9b0-438e-b7ba-91deca34af3d.png)
用easyTag看了下应该可以了。能用你的播放器看看吗？

**Comment by ironstress** [comment]
> ![image](https://user-images.githubusercontent.com/31397301/177898494-54869cc5-d1c7-4592-87d0-6e4f5a9275cf.png) ![image](https://user-images.githubusercontent.com/31397301/177898506-e05cf332-f9b0-438e-b7ba-91deca34af3d.png) 用easyTag看了下应该可以了。能用你的播放器看看吗？

1.6.6.6 确实可以了
