### ISSUE TITLE
使用手机号登录，提示当前登录存在安全风险，请稍候再试

### ISSUE THREAD

**Issue by smilejoker365** [mos9527/pyncm#18]
具体返回的信息如下

Traceback (most recent call last):
  File "/usr/local/bin/pyncm", line 8, in <module>
    sys.exit(__main__())
  File "/usr/local/lib/python3.10/dist-packages/pyncm/__main__.py", line 490, in __main__
    login.LoginViaCellphone(args.phone, args.pwd)
  File "/usr/local/lib/python3.10/dist-packages/pyncm/apis/login.py", line 135, in LoginViaCellphone
    WriteLoginInfo(login_status)
  File "/usr/local/lib/python3.10/dist-packages/pyncm/apis/login.py", line 27, in WriteLoginInfo
    raise LoginFailedException(sess.login_info["content"])
pyncm.apis.LoginFailedException: {'loginType': 1, 'code': 10003, 'message': '当前登录存在安全风险，请 稍后再试'}

请问大佬，这个应该如何解决啊

**Comment by smilejoker365** [comment]
> 暂时无法重现，先换了个新接口
> 
> 能帮忙测试试试看吗？

还是一样的提示，关于这个问题，我询问了网易云音乐的客服，客服告诉我因为短时间内登录次数太多，需要等24小时重试或更换设备。此行为系系统自动识别，无法人工干预。

**Comment by mos9527** [comment]
> > 暂时无法重现，先换了个新接口
> > 能帮忙测试试试看吗？
> 
> 还是一样的提示，关于这个问题，我询问了网易云音乐的客服，客服告诉我因为短时间内登录次数太多，需要等24小时重试或更换设备。此行为系系统自动识别，无法人工干预。

"更换设备" 倒挺有意思的，等会看看能不能在这个方面做文章

加了个[手机验证码登陆](https://github.com/mos9527/pyncm/blob/master/demos/%E6%89%8B%E6%9C%BA%E7%99%BB%E5%BD%95.py)，运行这个看看会不会一样报错？

**Comment by smilejoker365** [comment]
> > > 暂时无法重现，先换了个新接口
> > > 能帮忙测试试试看吗？
> > 
> > 
> > 还是一样的提示，关于这个问题，我询问了网易云音乐的客服，客服告诉我因为短时间内登录次数太多，需要等24小时重试或更换设备。此行为系系统自动识别，无法人工干预。
> 
> "更换设备" 倒挺有意思的，等会看看能不能在这个方面做文章
> 
> 加了个[手机验证码登陆](https://github.com/mos9527/pyncm/blob/master/demos/%E6%89%8B%E6%9C%BA%E7%99%BB%E5%BD%95.py)，运行这个看看会不会一样报错？

手机验证码没有报错，同时我这边密码登录也没有报错了。我估计昨天因为我用vps运行，本身是国外IP，所以风控几率变大了。今天用国内的vps运行，目前一切正常
