### ISSUE TITLE
部分文件名，发生保存失败

### ISSUE THREAD

**Issue by AsuZSH** [mos9527/pyncm#19]
URL:  "https://music.163.com/m/album?id=37256090"
测试命令: `pyncm --max-workers 8 --template "{artists} - {track}" --quality lossless  --lyric-no romalrc --load "login.dat" --http --log-level LOG_LEVEL "https://music.163.com/m/album?id=37256090"`
ps: 上述命令中login.dat 需要替换

失败歌曲名称：Aimer - Ref:rain
结果: Aimer - Ref ，留下一个无法播放的文件
如图: 
![image](https://user-images.githubusercontent.com/65713657/185819608-13a38fc3-fa1b-4556-962f-63af0c0c77b1.png)

感谢作者！！

**Comment by AsuZSH** [comment]
貌似替换特殊字符就可以。。：

希望作者看到🤣
    修正windows的符号问题
    “?”、“、”、“╲”、“/”、“*”、““”、“”“、“<”、“>”、“|” " " ":"

**Comment by mos9527** [comment]
1.6.7.2  修正了“--template”制定格式后文件名非法字符不被替换成全角版本的问题，
更新后试试看？

**Comment by AsuZSH** [comment]
可以使用了，nice感谢！！
