### ISSUE TITLE
如何同时管理多个多个账户、SessionManager

### ISSUE THREAD

**Issue by 286844626** [mos9527/pyncm#22]
我看SessionManager只能存在一个，同时登录多个会被覆盖，请问有什么好的办法解决吗

**Comment by mos9527** [comment]
尝试利用 `with` 语法实现了一个 Session 热切换，可以看看[API 使用示例](https://github.com/mos9527/pyncm#api-%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B)
