### ISSUE TITLE
有签到和刷歌的API吗

### ISSUE THREAD

**Issue by vbnetvbnet** [mos9527/pyncm#23]
api里好像有签到的函数，有没有刷歌的呢

**Comment by mos9527** [comment]
看看这个？[足迹伪装.py](https://github.com/mos9527/pyncm/blob/master/demos/%E8%B6%B3%E8%BF%B9%E4%BC%AA%E8%A3%85.py)

**Comment by vbnetvbnet** [comment]
非常感谢！

**Comment by vbnetvbnet** [comment]
尝试了下，好像无效？  刷了100多首了，绝对有没听过的，返回结果都是 `{'code': 200, 'data': 'success', 'message': ''}` 
但是 https://music.163.com/#/user/level  歌曲数就是没变化
