### ISSUE TITLE
上传云盘不能用了：SetUploadCloudInfo 返回404

### ISSUE THREAD

**Issue by vbnetvbnet** [mos9527/pyncm#24]
调用顺序：
login ...
GetNosToken
SetUploadObject
SetUploadCloudInfo （这一步返回 code 404 ） -- 前几天还没问题

试了下，用windows客户端可以正常上传

**Comment by mos9527** [comment]
刚刚试了下无法复现，看看[`demos/云盘上传.py`?]
(https://github.com/mos9527/pyncm/blob/master/demos/%E4%BA%91%E7%9B%98%E4%B8%8A%E4%BC%A0.py)
```
[DEBU] pyncm.api API=EAPI POST url=/eapi/cloud/pub/v2 deviceId=pyncm! payload={'songid': '2005830629'}
[DEBU] urllib3.connectionpool https://music.163.com:443 "POST /eapi/cloud/pub/v2 HTTP/1.1" 200 1302
发布结果 {'privateCloud': {'simpleSong': {'name': '...```

**Comment by vbnetvbnet** [comment]
额。。我也刚刚重新试了下，上传成功了！
白天确实一直失败，半小时之前还是一直失败的，可能是我网络不稳定..
