### ISSUE TITLE
GetTrackAudioV1 与 GetTrackAudio 这两个函数有什么不同

### ISSUE THREAD

**Issue by Quandong-Zhang** [mos9527/pyncm#27]
如题.

**Comment by mos9527** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/commit/647396f38ce4cc33acf303d37ce06f91500f63cf

**Comment by Quandong-Zhang** [comment]
> [Binaryify/NeteaseCloudMusicApi@647396f](https://github.com/Binaryify/NeteaseCloudMusicApi/commit/647396f38ce4cc33acf303d37ce06f91500f63cf)

感谢！
