### ISSUE TITLE
likelist接口未找到

### ISSUE THREAD

**Issue by adrzhou** [mos9527/pyncm#28]
您好！因为我看到 [Binaryify/NeteaseCloudMusicAPI](https://github.com/Binaryify/NeteaseCloudMusicApi) 中提供了[获取已喜欢音乐 id 列表](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e5%96%9c%e6%ac%a2%e9%9f%b3%e4%b9%90%e5%88%97%e8%a1%a8)的功能，所以想把这个功能也添加到pyncm的API中，但是每次调用的时候后都会显示找不到likelist接口。我写的函数是这样的：

```
@WeapiCryptoRequest
@UserIDBasedApi
@LoginRequiredApi
def GetUserLikeList():
    """网页端 - 获取某用户已喜欢音乐

    Args:
        user_id (int): 用户 ID。置 0 表示当前已登录的用户 . defaults to 0

    Returns:
        dict
    """
    return "/weapi/likelist", {
        "uid": str(user_id)
    }
```

**Comment by mos9527** [comment]
`/likelist`只是`NeteaseCloudMusicAPI`接口的导出，其impl在https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/likelist.js

看上去实际的路径应该是`/weapi/song/like/get`，还请修改试试

**Comment by adrzhou** [comment]
成功了！谢谢！
