### ISSUE TITLE
真的不会用代码

### ISSUE THREAD

**Issue by martjay** [mos9527/pyncm#29]
能不能一步步的给我示例代码？》

**Comment by mos9527** [comment]
README提供了[命令行](https://github.com/mos9527/pyncm#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B)和[API](https://github.com/mos9527/pyncm#api-%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B) 的使用示例，及相关[例程](https://github.com/mos9527/pyncm/tree/master/demos) ，建议先读完这些部分
遇到问题还请及时提交issue
毕竟解释这些代码要比在没有需求的前提下“一步步地给示例代码”要现实一些😅

**Comment by martjay** [comment]
> README提供了[命令行](https://github.com/mos9527/pyncm#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B)和[API](https://github.com/mos9527/pyncm#api-%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B) 的使用示例，及相关[例程](https://github.com/mos9527/pyncm/tree/master/demos) ，建议先读完这些部分 遇到问题还请及时提交issue 毕竟解释这些代码要比在没有需求的前提下“一步步地给示例代码”要现实一些😅

用了新版，确实可以下载了谢谢咯，但是会有一些提示“你大概是没登陆或者缺少钞能力”，如果能破就好了

**Comment by martjay** [comment]
> README提供了[命令行](https://github.com/mos9527/pyncm#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B)和[API](https://github.com/mos9527/pyncm#api-%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B) 的使用示例，及相关[例程](https://github.com/mos9527/pyncm/tree/master/demos) ，建议先读完这些部分 遇到问题还请及时提交issue 毕竟解释这些代码要比在没有需求的前提下“一步步地给示例代码”要现实一些😅

我是真的不会用代码，用exe又显示“参数错误”

**Comment by mos9527** [comment]
抱歉回复晚了，最近没太多时间查issue
能说下“参数错误”具体是什么问题吗？有截图说明会方便些

**Comment by martjay** [comment]
> 抱歉回复晚了，最近没太多时间查issue 能说下“参数错误”具体是什么问题吗？有截图说明会方便些

![Uploading 666666.jpg…]()

**Comment by mos9527** [comment]
最新的release应该可以运行了，试试看？

**Comment by martjay** [comment]
> 最新的release应该可以运行了，试试看？

打开后显示类似CMD窗口，然后闪退了
