### ISSUE TITLE
通过网页端获取他人歌单只有20条信息

### ISSUE THREAD

**Issue by ZTG0421** [mos9527/pyncm#31]
更新获取歌单内歌曲接口

**Comment by ZTG0421** [comment]
>

**Comment by ZTG0421** [comment]
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e8%8e%b7%e5%8f%96%e6%ad%8c%e5%8d%95%e6%89%80%e6%9c%89%e6%ad%8c%e6%9b%b2

**Comment by mos9527** [comment]
歌单API只能获取到完整`trackIds`字段，`tracks`字段在登录时也只能获取最多20个字段。官方貌似没有能获取完整`tracks`的歌单API。


> NeteaseCloudMusicApi的实现方法 https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/playlist_track_all.js

这里的实现也没有绕过上文提到的限制。[`pyncm`其实有类似思路的实现](https://github.com/mos9527/pyncm/blob/master/pyncm/__main__.py#L294-L295) ，可供参考。
鉴于该功能不属于官方API范畴，暂时不考虑在`pyncm`包内直接提供。

**Comment by ZTG0421** [comment]
![微信图片_20230109135532](https://user-images.githubusercontent.com/79940512/211248189-e50c2425-584e-4ca3-8379-73040b85422d.jpg)
![微信图片_20230109135537](https://user-images.githubusercontent.com/79940512/211248207-50360408-bb07-4c7a-b71d-91d32d275b1c.png)

**Comment by ZTG0421** [comment]
通过NeteaseCloudMusicApi的方法的确获取到了完整歌单，他也许使用了客户端的请求方法？
