### ISSUE TITLE
能否添加一个获取歌手的专辑列表+歌曲列表的 API

### ISSUE THREAD

**Issue by HYDlink** [mos9527/pyncm#33]
如果可以的话下载的时候能够支持 artist 的链接就好了

NeteaseCloudMusicApi 的实现
- https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/artist_songs.js
- https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/artist_albums.js

**Comment by mos9527** [comment]
[已加入API实现](https://github.com/mos9527/pyncm/commit/e937647f93d28e1531c2579cc265c3c9ef25c5a7#diff-bfb42c39f73d5fc66efb1558e7989aa07b433ce0ca4c1f006a26e281094d6873)

> 如果可以的话下载的时候能够支持 artist 的链接就好了

这点的实用性倒值得商榷
毕竟下载艺术家的所有歌曲/专辑不太像主流用途
而且借助网易云的歌单系统也能达到相应目的
这个等会再加吧🫤

**Comment by mos9527** [comment]
命令行实现做好了
注意使用 `-n` `--sort_by` 选项限制下载数目
