### ISSUE TITLE
在下载playlist时, 是否可以添加创建m3u播放列表的选项

### ISSUE THREAD

**Issue by sunkyzz** [mos9527/pyncm#34]
支持subsonic api的播放器基本都支持自动导入m3u文件, 这样可以实现将网易云播放列表无损迁移到navidrome这样的本地播放器上

**Comment by mos9527** [comment]
试试这些参数
```
限量及过滤（注：只适用于*每单个*链接 / ID）:
  -n 下载总量, --count 下载总量
                        限制下载歌曲总量，n=0即不限制
  --sort-by 歌曲排序        【限制总量时】歌曲排序方式 (default: 默认排序 hot: 热度高（相对于其所在专辑）在前 time: 发行时间新在前)
  --reverse-sort        【限制总量时】倒序排序歌曲

工具:
  --save-m3u 保存M3U播放列表文件名
                        将本次下载的歌曲文件名依一定顺序保存在M3U文件中；写入的文件目录相对于该M3U文件
                                文件编码为 UTF-8
                                顺序为：链接先后优先——每个连接的所有歌曲依照歌曲排序设定 （--sort-by）排序
```

**Comment by sunkyzz** [comment]
> 试试这些参数
> 
> ```
> 限量及过滤（注：只适用于*每单个*链接 / ID）:
>   -n 下载总量, --count 下载总量
>                         限制下载歌曲总量，n=0即不限制
>   --sort-by 歌曲排序        【限制总量时】歌曲排序方式 (default: 默认排序 hot: 热度高（相对于其所在专辑）在前 time: 发行时间新在前)
>   --reverse-sort        【限制总量时】倒序排序歌曲
> 
> 工具:
>   --save-m3u 保存M3U播放列表文件名
>                         将本次下载的歌曲文件名依一定顺序保存在M3U文件中；写入的文件目录相对于该M3U文件
>                                 文件编码为 UTF-8
>                                 顺序为：链接先后优先——每个连接的所有歌曲依照歌曲排序设定 （--sort-by）排序
> ```

好的 感谢
