### ISSUE TITLE
考虑支持异步吗？

### ISSUE THREAD

**Issue by z0z0r4** [mos9527/pyncm#36]
显然异步对于爬虫可能很有用

**Comment by mos9527** [comment]
未来可能会用aiohttp重构成async模式，不过目前没时间弄🫤
暂时可以考虑[run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor)妥协一下，记得用threadpool

**Comment by z0z0r4** [comment]
> 未来可能会用aiohttp重构成async模式，不过目前没时间弄🫤 暂时可以考虑[run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor)妥协一下，记得用threadpool

如果可能，我会在 https://github.com/z0z0r4/async-pyncm 实现，当然同样也没啥时间...高一生

**Comment by mos9527** [comment]
试着重构了下，已经挂在pypi了：[pyncm-async](https://pypi.org/project/pyncm-async/)
异步部分分支到了`async` branch,新codebase没有之前的helper部分
简单测试了下貌似效果ok？不过我不熟悉async，希望能帮忙看看

**Comment by z0z0r4** [comment]
> 试着重构了下，已经挂在pypi了：[pyncm-async](https://pypi.org/project/pyncm-async/) 异步部分分支到了`async` branch,新codebase没有之前的helper部分 简单测试了下貌似效果ok？不过我不熟悉async，希望能帮忙看看

关于 [pyncm-async](https://pypi.org/project/pyncm-async/) 是暂时实在没空看，今天高考假结束，我下次能摸到电脑是暑假了...

暑假来尽力.jpg

**Comment by mos9527** [comment]
> > 试着重构了下，已经挂在pypi了：[pyncm-async](https://pypi.org/project/pyncm-async/) 异步部分分支到了`async` branch,新codebase没有之前的helper部分 简单测试了下貌似效果ok？不过我不熟悉async，希望能帮忙看看
> 
> 关于 [pyncm-async](https://pypi.org/project/pyncm-async/) 是暂时实在没空看，今天高考假结束，我下次能摸到电脑是暑假了...
> 
> ~暑假来尽力.jpg~
> 
> 看了看，如果测试的能跑大概就是没问题的...（雾，云review

😂我高考假才刚开始
有时间再说吧？

对了，我主动pull了你的repo，不过github上的contributors看不到你🤕
之后试试看再提交个pr？credit还是要有的🤔

**Comment by z0z0r4** [comment]
> > > 试着重构了下，已经挂在pypi了：[pyncm-async](https://pypi.org/project/pyncm-async/) 异步部分分支到了`async` branch,新codebase没有之前的helper部分 简单测试了下貌似效果ok？不过我不熟悉async，希望能帮忙看看
> > 
> > 
> > 关于 [pyncm-async](https://pypi.org/project/pyncm-async/) 是暂时实在没空看，今天高考假结束，我下次能摸到电脑是暑假了...
> > ~暑假来尽力.jpg~
> > 看了看，如果测试的能跑大概就是没问题的...（雾，云review
> 
> 😂我高考假才刚开始 有时间再说吧？
> 
> 对了，我主动pull了你的repo，不过github上的contributors看不到你🤕 之后试试看再提交个pr？credit还是要有的🤔

算了吧，没必要
