### ISSUE TITLE
下载失败，无法下载，资源不存在

### ISSUE THREAD

**Issue by Rongyimin-z** [mos9527/pyncm#41]
![image](https://github.com/mos9527/pyncm/assets/52277121/eba1ab80-41ad-4bdb-a766-dc54403382bb)

**Comment by mos9527** [comment]
歌曲需要VIP
![image](https://github.com/mos9527/pyncm/assets/31397301/9ad9a89a-33c2-437a-b7f1-fecc1250f12d)
一定要下载的话可以考虑看看[UnblockNeteaseMusic](https://github.com/mos9527/pyncm#%E4%BD%BF%E7%94%A8-unm-%E4%B8%8B%E8%BD%BD%E7%81%B0%E8%89%B2%E6%AD%8C%E6%9B%B2)

**Comment by Rongyimin-z** [comment]
好滴，了解，只是现在云村随便一首歌下载好像都要会员
