### ISSUE TITLE
[FR] 支持下载一个用户的所有歌单

### ISSUE THREAD

**Issue by glyh** [mos9527/pyncm#43]
如题。希望增加一个选项，根据保存的登陆信息读取创建的所有歌单，然后自动同步到本地（类似rsync）。

并且希望支持提供--delete 选项（自动删除本地不在歌单里的歌曲）

**Comment by mos9527** [comment]
已加入用户歌单下载
提供用户主页分享链接即可，如 `https://music.163.com/#/user/home?id=315542615`
默认只下载用户创建的歌单。需要下载收藏歌单可使用 `--user-bookmarks` Flag，详情见 README
要求不覆写已存在歌曲可使用 `--no-overwrite`

`--delete` 侵入程度较大，就不在cli实现了。把这个feature做成demo如何🤔

**Comment by glyh** [comment]
支持做成demo

**Comment by mos9527** [comment]
[歌单同步.py](https://github.com/mos9527/pyncm/blob/master/demos/%E6%AD%8C%E5%8D%95%E5%90%8C%E6%AD%A5.py)
试试看？传参和`pyncm`完全一致，看看文件吧。

**Comment by glyh** [comment]
谢谢！我个人希望可以把m3u文件分开。我研究一下这个demo

**Comment by mos9527** [comment]
> 谢谢！我个人希望可以把m3u文件分开。我研究一下这个demo.
> 
> EDIT: 大概需要重复调用__main__多次？
可以在歌单同步登陆后(Line 20)获取所有歌单 ID (参考 https://github.com/mos9527/pyncm/blob/master/pyncm/__main__.py#L451)
然后对每个 ID 调用
调用可以通过改变`argv`末项改变歌单 ID，然后调用`__main__`
