### ISSUE TITLE
无法下载 Hi-Res 版本的歌曲

### ISSUE THREAD

**Issue by Aalivexy** [mos9527/pyncm#44]
示例连接：
`https://music.163.com/#/song?id=1882642256`

虽然标注为 `CVIP`，但实际上是可以免费下载 `Hi-Res` 版本的

**Comment by mos9527** [comment]
试不出免费下hires😂
不过好像下hires都要VIP了？
![image](https://github.com/mos9527/pyncm/assets/31397301/6c9592b6-887b-4ff5-a987-836094528081)

**Comment by Aalivexy** [comment]
我使用的android app，确实是可以
![Screenshot_2023-08-09-08-57-23-096_com netease cloudmusic-edit](https://github.com/mos9527/pyncm/assets/136234776/c77c43db-1b84-4ae3-b339-84410bd40917)
![Screenshot_2023-08-09-08-57-38-375_com netease cloudmusic](https://github.com/mos9527/pyncm/assets/136234776/018a9faf-650e-462a-b2f3-32d4a73cd4b2)
![IMG_20230809_090006](https://github.com/mos9527/pyncm/assets/136234776/0dc97dc5-2cc5-49b8-9b11-cc9f6788ecea)
![Screenshot_2023-08-09-08-58-51-077_com netease cloudmusic-edit](https://github.com/mos9527/pyncm/assets/136234776/f7fe8ca5-b798-4c76-886a-25db5e37042e)

**Comment by Aalivexy** [comment]
总不能是我出bug了吧233333
这样下载下来的flac会比mp3多个1~2MB，20kHz以上都有保留（mp3就一刀切了）

**Comment by mos9527** [comment]
![image](https://github.com/mos9527/pyncm/assets/31397301/01b6fd45-aa74-4e2e-b3b3-e7eb5ccd3909)
重现ok，用新版本加上`--use-download-api` Flag 试试？
注意这样的下载会计入下载额度，可以看看 https://music.163.com/member/downinfo

**Comment by Aalivexy** [comment]
好快的码！确实可以用了！
~~其实只要没有VIP就不需要担心额度问题吧~~
