### ISSUE TITLE
关于开代理/梯子后pyncm报错的问题

### ISSUE THREAD

**Issue by RealityError** [mos9527/pyncm#46]
开了代理之后pyncm老是报错，我去单独的模块下面设置后就没问题了。
所以调用api的时候可以在哪里设置全局代理吗？
![image](https://github.com/mos9527/pyncm/assets/67266280/fbf4ffd1-8560-4c5c-996e-55e21a98be33)
![image](https://github.com/mos9527/pyncm/assets/67266280/086f7b69-8b11-4c1b-99fa-3206433f538b)

**Comment by mos9527** [comment]
使用 `GetCurrentSession` 可取得 `pyncm` 正在使用的 Session, 其本质上为 `requests` 的 `Session` 的wrapper
故设置其代理和设置`requests.Session`代理一致。配置（或清除）全局代理参下：
```python
from pyncm import GetCurrentSession
GetCurrentSession.proxies = {'http': None, 'https': None}
```
其次清除相关环境变量也可以达成一致效果，参见：
https://requests.readthedocs.io/projects/cn/zh_CN/latest/user/advanced.html?highlight=http_proxy#proxies

**Comment by RealityError** [comment]
好的，谢谢解答
