### ISSUE TITLE
似乎异步分支无法正常使用DumpSessionAsString

### ISSUE THREAD

**Issue by applenana** [mos9527/pyncm#49]
![_PZ{}6U~TOKVP1~H`{2HX~Y](https://github.com/mos9527/pyncm/assets/83851967/40a5c7df-0b3b-4ed0-8d1b-7b700a34e158)
我在使用如上的代码片段是，总会报错，如下
![(TQ7PVZ Z% 2P~KOY0R EMT](https://github.com/mos9527/pyncm/assets/83851967/7db2de60-841a-4577-9a47-77ff4ea4d9ab)
但是改用同步的代码又能使用，如下
![PNKZ7J@K_Z%ZI(7I E2~1YE](https://github.com/mos9527/pyncm/assets/83851967/677fb8f2-6bba-45a1-93a8-1e87d1a67231)

**Comment by mos9527** [comment]
0.0.2已修复
