### ISSUE TITLE
cloudsearch.GetSearchResult 返回 {'code': 50000005}

### ISSUE THREAD

**Issue by MistEO** [mos9527/pyncm#50]
![image](https://github.com/mos9527/pyncm/assets/18511905/376c5de9-7500-4964-971f-50b6e4e23419)

之前一直都是好的，是不是最近网易云 API 改了？

使用的版本是 pyncm-1.6.11

**Comment by MistEO** [comment]
其他接口简单试了下还是没问题的

![image](https://github.com/mos9527/pyncm/assets/18511905/338f69b9-fbe6-46ba-89a6-59d7cde3e3c9)

**Comment by mos9527** [comment]
![image](https://github.com/mos9527/pyncm/assets/31397301/f045f1a1-1743-4d5c-ae34-7c5a0c7364d5)
[fixed in 1.6.12](https://github.com/mos9527/pyncm/commit/eb9b887fcfdb0755bbf3d99fe40cfd74387141af)

**Comment by MistEO** [comment]
感谢！
