### ISSUE TITLE
当前登录存在安全风险，请稍候再试

### ISSUE THREAD

**Issue by sakanadesu0449** [mos9527/pyncm#53]
最新版api
使用手机密码和验证码均无效

**Comment by sakanadesu0449** [comment]
![err](https://github.com/mos9527/pyncm/assets/128910565/38f9f3d1-0a5e-44d2-845c-049a4383af6e)

**Comment by mos9527** [comment]
抱歉，暂时无法复现
![image](https://github.com/mos9527/pyncm/assets/31397301/7e6a37b7-47af-4aad-8328-da1cca0d9a32)
或许可以尝试使用官方客户端登陆该账号
错误同 #51

**Comment by sakanadesu0449** [comment]
好的谢谢，也许是号被网易云风控了
