### ISSUE TITLE
pyncm-async 不支持 with session语法

### ISSUE THREAD

**Issue by nneowvoincee** [mos9527/pyncm#54]
![image](https://github.com/mos9527/pyncm/assets/72647845/4013138a-91b8-4e79-aac2-76a58cfc20dc)

`  <pyncm_async.Session object at 0x0000020E1EC62C90> 
File "C:\Users\PycharmProjects\test\main.py", line 9, in search
    with session:
TypeError: 'Session' object does not support the context manager protocol
`
但是如果用同步的pyncm就没有这个问题。
是否对于多session，异步和同步的使用方法不一样？

**Comment by nneowvoincee** [comment]
problem solved. I forgot add `await ` before `with`.

**Comment by mos9527** [comment]
[新README](https://github.com/mos9527/pyncm/blob/async/README.md#api-%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B-ipython)已跟进，多谢指出！
