### ISSUE TITLE
列表乱序问题

### ISSUE THREAD

**Issue by ZTG0421** [mos9527/pyncm#56]
调用pyncm.apis.track.GetTrackAudio(id_list)时，返回的数据result['data']是乱序的

**Comment by ZTG0421** [comment]
或许可以增加一个参数来自动修复乱序问题？

**Comment by mos9527** [comment]
没能找到相关API参数确定收到的数据顺序，抱歉
不过手动处理貌似也比较方便？
```python
ids = [2095543413, 2095543414, 2095543415, 2095543416]
result = track.GetTrackAudio(ids)
tracks = [{item['id']:item for item in result['data']}[tid] for tid in ids]
```
暂时不考虑向API中加入这种post process，毕竟不能保证上游的数据格式一定不变。这点就交给用户处理了
