### ISSUE TITLE
手机号和二维码都登录不了

### ISSUE THREAD

**Issue by Janzjoy** [mos9527/pyncm#68]
![image](https://github.com/user-attachments/assets/8e303e94-1b9d-43f5-81e5-b7bc4b6733a1)
能不能加一个cookie加载 Session啊

**Comment by mos9527** [comment]
本地测试暂时无法复现手机登录异常；在同一网络环境/代理配置下使用官方客户端登录相同账号可能缓解限流问题，具体限制暂时未知
此外，[Cookie登录已在1.7.0实现](https://github.com/mos9527/pyncm/commit/932576d5a28e634baedd3bb188c3038a8297c9d5)
- Python API 为 `login.LoginViaCookie(MUSIC_U=...)`；其中 `MUSIC_U` 为所需的唯一Cookie值，传入形如`00B2471D143...`参即可
- CLI大同小异，使用`--cookie`指定即可

**Comment by Janzjoy** [comment]
> 本地测试暂时无法复现手机登录异常；在同一网络环境/代理配置下使用官方客户端登录相同账号可能缓解限流问题，具体限制暂时未知 此外，[Cookie登录已在1.7.0实现](https://github.com/mos9527/pyncm/commit/932576d5a28e634baedd3bb188c3038a8297c9d5)
> 
> * Python API 为 `login.LoginViaCookie(MUSIC_U=...)`；其中 `MUSIC_U` 为所需的唯一Cookie值，传入形如`00B2471D143...`参即可
> * CLI大同小异，使用`--cookie`指定即可

好的
